### ISSUE TITLE
UX for ADA Compliant Venues

### ISSUE THREAD

**Issue by jeremylow** [PhillyDSA/phillydsa-com#8]
## Expected Behavior

We would like to display on each event page whether or not the venue is ADA compliant. This information is somewhat difficult to track down unfortunately, but it is exceedingly worthwhile to do so. At a minimum, we should encourage event staff to affirmatively state whether or not a location or venue is wheelchair accessible. 

## Current Behavior

There is no indication of whether a venue is wheelchair accessible or ADA compliant, meaning our members are left in the dark as to possible access.

## Possible Solution

For any event, we should have a field on the event that delineates whether or not the venue is ADA compliant. The expected values are `Yes`, `No`, `Unknown`. To the degree possible, the use of `Unknown` should be discouraged and possibly eliminated entirely.

## Context

Our disabled members are unlikely to come out to our events if this information is not affirmatively provided, leading to the appearance that we have fewer disabled members than we do. It is incumbent on our chapter (or any chapter really) to ensure that this inference is not made because of the choices our abled members make.

## Your Environment

* Version used (if applicable): `0.23.1`

**Comment by MBLAHO13** [comment]
As a followup, we should also have a field for ASL interpretation as well. 

There is a small symbol for wheelchair accessibility: **♿** There is also a newer, more aesthetically pleasing and respectful icon designed by Triangle, but this would require an asset on the site (that emoji renders differently on different platforms): http://accessibleicon.org/#use

For ASL interpretation/hearing access, there are some symbols on this page: https://www.graphicartistsguild.org/tools_resources/downloadable-disability-access-symbols . 

And, we should attach alt-text to said assets so that people can hear a description of the specific accommodations.

**Comment by jeremylow** [comment]
landed in develop with #10
